// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GradRecruitmentDbContext))]
    [Migration("20260805120000_AddTechnicalRatingToApplicationRecord")]
    partial class AddTechnicalRatingToApplicationRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CandidateEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CandidateEmail");

                    b.Property<string>("CandidateGitHubUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("CandidateGitHubUrl");

                    b.Property<string>("CandidateName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CandidateName");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ClaimedAt");

                    b.Property<string>("ClaimedByRecruiterId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ClaimedByRecruiterId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CvAttachmentId")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("CvAttachmentId");

                    b.Property<string>("CvSummary")
                        .HasColumnType("text")
                        .HasColumnName("CvSummary");

                    b.Property<string>("EmailMessageId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("EmailMessageId");

                    b.Property<string>("FlagsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("FlagsJson");

                    b.Property<bool?>("HardGatePassed")
                        .HasColumnType("boolean")
                        .HasColumnName("HardGatePassed");

                    b.Property<string>("HardGateReason")
                        .HasMaxLength(504)
                        .HasColumnType("character varying(504)")
                        .HasColumnName("HardGateReason");

                    b.Property<string>("HiringAgentExplanation")
                        .HasColumnType("text")
                        .HasColumnName("HiringAgentExplanation");

                    b.Property<decimal?>("HiringAgentTotalScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("HiringAgentTotalScore");

                    b.Property<DateTimeOffset?>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RatedAt");

                    b.Property<string>("RatedByRecruiterId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("RatedByRecruiterId");

                    b.Property<short?>("RecruiterRating")
                        .HasColumnType("smallint")
                        .HasColumnName("RecruiterRating");

                    b.Property<string>("RecruiterRatingNote")
                        .HasColumnType("text")
                        .HasColumnName("RecruiterRatingNote");

                    b.Property<short?>("TechnicalRating")
                        .HasColumnType("smallint")
                        .HasColumnName("TechnicalRating");

                    b.Property<DateTimeOffset?>("ShortlistedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ShortlistedAt");

                    b.Property<string>("ShortlistedByRecruiterId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ShortlistedByRecruiterId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<string>("Tier")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Tier");

                    b.Property<string>("TranscriptAttachmentId")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("TranscriptAttachmentId");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId")
                        .IsUnique()
                        .HasDatabaseName("UQ_EmailMessageId");

                    b.ToTable("ApplicationRecords", null, t =>
                        {
                            t.HasCheckConstraint("ApplicationRecords_RecruiterRating_check", "\"RecruiterRating\" BETWEEN 1 AND 5");
                            t.HasCheckConstraint("ApplicationRecords_TechnicalRating_check", "\"TechnicalRating\" BETWEEN 1 AND 5");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
