// <auto-generated />
using System;
using System.Text.Json;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GradRecruitmentDbContext))]
    partial class GradRecruitmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CandidateEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CandidateEmail");

                    b.Property<string>("CandidateGitHubUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("CandidateGitHubUrl");

                    b.Property<string>("CandidateName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CandidateName");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ClaimedAt");

                    b.Property<string>("ClaimedByRecruiterId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ClaimedByRecruiterId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CvAttachmentId")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("CvAttachmentId");

                    b.Property<string>("CvSummary")
                        .HasColumnType("text")
                        .HasColumnName("CvSummary");

                    b.Property<string>("EmailMessageId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("EmailMessageId");

                    b.Property<JsonDocument>("FlagsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("FlagsJson");

                    b.Property<bool?>("HardGatePassed")
                        .HasColumnType("boolean")
                        .HasColumnName("HardGatePassed");

                    b.Property<string>("HardGateReason")
                        .HasMaxLength(504)
                        .HasColumnType("character varying(504)")
                        .HasColumnName("HardGateReason");

                    b.Property<string>("HiringAgentExplanation")
                        .HasColumnType("text")
                        .HasColumnName("HiringAgentExplanation");

                    b.Property<decimal?>("HiringAgentTotalScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("HiringAgentTotalScore");

                    b.Property<DateTimeOffset?>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RatedAt");

                    b.Property<string>("RatedByRecruiterId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("RatedByRecruiterId");

                    b.Property<short?>("RecruiterRating")
                        .HasColumnType("smallint")
                        .HasColumnName("RecruiterRating");

                    b.Property<string>("RecruiterRatingNote")
                        .HasColumnType("text")
                        .HasColumnName("RecruiterRatingNote");

                    b.Property<short?>("TechnicalRating")
                        .HasColumnType("smallint")
                        .HasColumnName("TechnicalRating");

                    b.Property<DateTimeOffset?>("ShortlistedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ShortlistedAt");

                    b.Property<string>("ShortlistedByRecruiterId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ShortlistedByRecruiterId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<string>("Tier")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Tier");

                    b.Property<string>("TranscriptAttachmentId")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("TranscriptAttachmentId");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId")
                        .IsUnique()
                        .HasDatabaseName("UQ_EmailMessageId");

                    b.ToTable("ApplicationRecords", null, t =>
                        {
                            t.HasCheckConstraint("ApplicationRecords_RecruiterRating_check", "\"RecruiterRating\" BETWEEN 1 AND 5");
                            t.HasCheckConstraint("ApplicationRecords_TechnicalRating_check", "\"TechnicalRating\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ApplicationRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("ApplicationRecordId");

                    b.Property<string>("ExceptionDetails")
                        .HasColumnType("text")
                        .HasColumnName("ExceptionDetails");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("LogLevel");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Message");

                    b.Property<string>("SourceService")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SourceService");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationRecordId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HiringAgentEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text")
                        .HasColumnName("AiSummary");

                    b.Property<Guid>("ApplicationRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("ApplicationRecordId");

                    b.Property<JsonDocument>("AreasForImprovementJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("AreasForImprovementJson");

                    b.Property<JsonDocument>("BonusPointsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("BonusPointsJson");

                    b.Property<JsonDocument>("CategoryScoresJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("CategoryScoresJson");

                    b.Property<JsonDocument>("DeductionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("DeductionsJson");

                    b.Property<JsonDocument>("EvidenceJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("EvidenceJson");

                    b.Property<JsonDocument>("GitHubProfileDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("GitHubProfileDataJson");

                    b.Property<JsonDocument>("InstitutionJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("InstitutionJson");

                    b.Property<JsonDocument>("KeyStrengthsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("KeyStrengthsJson");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ProcessedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<JsonDocument>("ProjectClassificationsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ProjectClassificationsJson");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationRecordId");

                    b.ToTable("HiringAgentEvaluations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Recruiter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FirstName");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("IdentityId");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LastName");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Recruiters_Email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Recruiters_IdentityId");

                    b.ToTable("Recruiters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RecruiterAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ActionType");

                    b.Property<DateTimeOffset>("ActionedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ActionedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ApplicationRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("ApplicationRecordId");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NewStatus");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PreviousStatus");

                    b.Property<short?>("RatingValue")
                        .HasColumnType("smallint")
                        .HasColumnName("RatingValue");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("Reason");

                    b.Property<string>("RecruiterIdentity")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("RecruiterIdentity");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationRecordId");

                    b.ToTable("RecruiterActions", null, t =>
                        {
                            t.HasCheckConstraint("RecruiterActions_RatingValue_check", "\"RatingValue\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationRecord", "ApplicationRecord")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ApplicationRecordId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AuditLogs_ApplicationRecords");

                    b.Navigation("ApplicationRecord");
                });

            modelBuilder.Entity("Domain.Entities.HiringAgentEvaluation", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationRecord", "ApplicationRecord")
                        .WithMany("HiringAgentEvaluations")
                        .HasForeignKey("ApplicationRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HiringAgentEvaluations_ApplicationRecords");

                    b.Navigation("ApplicationRecord");
                });

            modelBuilder.Entity("Domain.Entities.RecruiterAction", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationRecord", "ApplicationRecord")
                        .WithMany("RecruiterActions")
                        .HasForeignKey("ApplicationRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecruiterActions_ApplicationRecords");

                    b.Navigation("ApplicationRecord");
                });

            modelBuilder.Entity("Domain.Entities.ApplicationRecord", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("HiringAgentEvaluations");

                    b.Navigation("RecruiterActions");
                });
#pragma warning restore 612, 618
        }
    }
}
